# Generated by Django 3.1.6 on 2021-02-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yogacourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('instructor', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('L', 'Low'), ('M', 'Middle'), ('H', 'High')], default='M', max_length=1)),
                ('description', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
