# Generated by Django 3.1.6 on 2021-02-25 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yogastudio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogacourse',
            old_name='start_at',
            new_name='datetime_start',
        ),
        migrations.RemoveField(
            model_name='yogacourse',
            name='duration',
        ),
        migrations.AddField(
            model_name='yogacourse',
            name='start_end_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
