# Generated by Django 3.1.6 on 2021-02-25 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yogastudio', '0002_auto_20210225_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yogacourse',
            options={'ordering': ('-datetime_start',)},
        ),
        migrations.AddField(
            model_name='yogacourse',
            name='books',
            field=models.ManyToManyField(related_name='course_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
