# Generated by Django 3.1.6 on 2021-02-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogastudio', '0003_auto_20210225_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yogacourse',
            options={'ordering': ('datetime_start',)},
        ),
    ]
