# Generated by Django 3.1.6 on 2021-02-25 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yogastudio', '0004_auto_20210225_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogacourse',
            name='books',
            field=models.ManyToManyField(null=True, related_name='course_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
